<?xml version="1.0"?>
<robot name="gripper_task" xmlns:xacro="http://wiki.ros.org/xacro">

	<!-- define relative movement to get to gripper_description/ -->
	<xacro:property name="path_to_top" value="../.."/>

	<!-- load the gripper config information -->
	<xacro:property name="filename" value="${path_to_top}/config/gripper.yaml"/>
	<xacro:property name="yaml_dict" value="${load_yaml(filename)}"/>
	
	<!-- extract the gripper config information -->
	<xacro:property name="xy_base_joint" value="${yaml_dict['gripper_config']['xy_base_joint']}"/>
	<xacro:property name="z_base_rotation" value="${yaml_dict['gripper_config']['z_base_rotation']}"/>
	<xacro:property name="fingertip_clearance" value="${yaml_dict['gripper_params']['fingertip_clearance']}"/> 
	<xacro:property name="hook_length" value="${yaml_dict['gripper_params']['hook_length']}"/> 
	<xacro:property name="hook_angle_rad" value="${yaml_dict['gripper_params']['hook_angle_degrees'] * (3.141592 / 180.0)}"/> 

  <!-- include the mujoco settings xacro -->
	<xacro:include filename="${path_to_top}/mujoco/xacro/mujoco.xacro"/>
	<xacro:mujoco_settings/>

	<!-- include the gripper only -->
	<xacro:include filename="${path_to_top}/xacro/gripper.xacro"/>
	<xacro:add_gripper path_to_top="${path_to_top}"/>

	<!-- height for fingertips to just not touch the ground, then height to raise
	past that. Note that this height is calibrated manually using mujoco and with
  checking the wrist z sensor for contact. This is calibrated AFTER the gripper
	has settled (ie joint controller stiffness accounted for). See the function
	'calibrate_reset()' in myfunctions.cpp and turn on debug mode to see the final
	settled finger end height above the ground, you can use this to adjust the value
	of 'fingerend_touches_ground' so that a 'fingertip_clearance' of 0.0 gives a
	finger end height of 0.0 -->
	<xacro:property name="fingerend_touches_ground" value="${0.1407 + yaml_dict['gripper_params']['finger_length']}"/>
	<xacro:if value="${yaml_dict['gripper_params']['hook_angle_degrees'] > 90}">
		<xacro:property name="hook_extra" value="0.0"/>
	</xacro:if>
	<xacro:if value="${not (yaml_dict['gripper_params']['hook_angle_degrees'] > 90)}">
		<xacro:property name="hook_extra" value="${hook_length * cos(hook_angle_rad)}"/>
	</xacro:if>

	<xacro:property name="h" value="${fingerend_touches_ground + fingertip_clearance + hook_extra}"/>

  <!-- create gripper base joints in mujoco -->
	<xacro:if value="${xy_base_joint}">

		<!-- we want full XYZ movement of the gripper base -->
		<link name="world"/>

		<link name="base_XY">
			<inertial>
				<mass value="1.0"/>
				<inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3"/>
			</inertial>
		</link>
		
		<link name="base_YZ">
			<inertial>
				<mass value="1.0"/>
				<inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3"/>
			</inertial>
		</link>

		<joint name="base_X_joint" type="prismatic">
			<origin xyz="0 0 ${h}" rpy="${pi} 0 0"/>
			<axis xyz="1 0 0" rpy="0 0 0"/>
			<parent link="world"/>
			<child link="base_XY"/>
			<limit effort="1e3" 
						lower="-1"
						upper="1"
						velocity="1"/>
			<dynamics damping="1"/>
		</joint>

		<joint name="base_Y_joint" type="prismatic">
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<axis xyz="0 -1 0" rpy="$0 0 0"/>
			<parent link="base_XY"/>
			<child link="base_YZ"/>
			<limit effort="1e3" 
						lower="-1"
						upper="1"
						velocity="1"/>
			<dynamics damping="1"/>
		</joint>

		<xacro:if value="${z_base_rotation}">

			<link name="base_ZrotZ">
				<inertial>
					<mass value="1.0"/>
					<inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3"/>
				</inertial>
			</link>

			<joint name="base_Z_joint" type="prismatic">
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<axis xyz="0 0 1" rpy="0 0 0"/>
				<parent link="base_YZ"/>
				<child link="base_ZrotZ"/>
				<limit effort="1e3" 
							lower="-1"
							upper="1"
							velocity="1"/>
				<dynamics damping="1"/>
			</joint>

			<joint name="base_Z_rotation_joint" type="revolute">
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<axis xyz="0 0 1" rpy="0 0 0"/>
				<parent link="base_ZrotZ"/>
				<child link="gripper_base_link"/>
				<limit effort="1e3" 
							lower="-1000"
							upper="1000"
							velocity="1"/>
				<dynamics damping="1"/>
			</joint>

		</xacro:if>
		<xacro:if value="${not z_base_rotation}">

			<joint name="base_Z_joint" type="prismatic">
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<axis xyz="0 0 1" rpy="0 0 0"/>
				<parent link="base_YZ"/>
				<child link="gripper_base_link"/>
				<limit effort="1e3" 
							lower="-1"
							upper="1"
							velocity="1"/>
				<dynamics damping="1"/>
			</joint>

		</xacro:if>

	</xacro:if>
	<xacro:if value="${not xy_base_joint}">

		<!-- we only want Z movement of the gripper base -->
		<link name="world"/>
		<joint name="world_to_base" type="prismatic">
			<origin xyz="0 0 ${h}" rpy="${pi} 0 0"/>
			<axis xyz="0 0 1" rpy="0 0 0"/>
			<parent link="world"/>
			<child link="gripper_base_link"/>
			<limit effort="1e3" 
						lower="-1"
						upper="1"
						velocity="1"/>
			<dynamics damping="1"/>
		</joint>

	</xacro:if>
		
</robot> 
