gripper_config:
  effort_control: false
  is_segmented: true
  num_segments: 10
  previous_update:
    effort_control: false
    old_is_segmented: true
    old_num_segments: 10
    torsion: false
  torsion: false

params:
  xy_min: 49.0e-3
  xy_max: 134.0e-3
  z_min: 0.0e-3
  z_max: 165.0e-3
  finger_length: 235.0e-3
  hook_length: 38.5e-3