gripper_config:
  effort_control: false
  is_segmented: true
  num_segments: 10
  torsion: false

# all in SI units unless stated (m/rad) NB must use 0.0e-3 not 0e-3 for yaml
gripper_params:
  xy_min: 49.0e-3            # max - 32.0revs * (lead/gear ratio)
  xy_max: 134.0e-3           # set in Gripper_v2.h (arduino lib)
  xy_home: 131.33e-3         # max - 1.0revs * (lead/gear ratio)
  z_min: 0.0e-3              # set in Gripper_v2.h (arduino lib)
  z_max: 165.0e-3            # 34.0revs * (lead/gear ratio)
  z_home: 4.88e-3            # 1.0revs * (lead/gear ratio)
  finger_length: 235.0e-3    # measured
  finger_width: 28.0e-3      # measured
  finger_thickness: 0.9e-3   # measured
  finger_mass: 75.0e-3       # measured
  hook_length: 38.5e-3       # measured
  hook_angle_degrees: 90.0   # measured
  angle_max_abs: 0.7