gripper_config:
  effort_control: false
  fixed_first_segment: false
  fixed_hook_segment: false
  fixed_motor_joints: true
  is_segmented: true
  num_segments: 15
  torsion: false
  xy_base_joint: false
  xy_base_rotation: false
  z_base_rotation: false
gripper_params:
  angle_max_abs: 0.7
  finger_E: 193000000000.0
  finger_length: 0.235
  finger_mass: 0.075
  finger_thickness: 0.0009
  finger_width: 0.024
  fingertip_clearance: 0.1
  hook_angle_degrees: 90.0
  hook_length: 0.035
  segment_inertia_scaling: 1.0
  xy_home: 0.13133
  xy_max: 0.134
  xy_min: 0.049
  z_home: 0.00488
  z_max: 0.165
  z_min: 0.0
